name: Generate Snake Contribution

on:
  schedule:
    - cron: "0 0 * * *" # Run once a day at midnight (UTC)
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write # This grants permission to write files to the repository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v3
        with:
          github_user_name: sreya-s19 # <--- **THIS IS THE CRITICAL CHANGE**
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
